service: goalrilla-catalog-api

custom:
  # enable for environment variables
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-2
  environment:
    STAGE: ${self:provider.stage}
plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true
  include:
    - env.js.enc
    - envdotjs-key

functions:
  # V1 - use semver, increment version appended when breaking changes made
  requestCatalogV1:
    handler: src/handler.requestCatalogV1
    events:
      - http:
          path: catalog-requests
          method: post
          cors: true