service: serverless-boilerplate

custom:
  secrets: ${file(env.yml):prod}
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  # dev, stage, or prod
  stage: dev
  region: us-east-2
  environment:
    STAGE: ${self:provider.stage}
    # SECRET_VALUE: "${self:custom.secrets.SECRET_VALUE}"

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  # V1 - use semver, increment version appended when breaking changes made
  createV1:
    handler: src/handler.create
    events:
      - http:
          path: V1/endpoint
          method: post
          cors: true
  fetchV1:
    handler: src/handler.fetch
    events:
      - http:
          path: V1/endpoint/{myParam}
          method: get
          cors: true