service: serverless-boilerplate

custom:
  # enable for environment variables
  # secrets: ${file(env.yml):prod}
  webpackIncludeModules: true

provider:
  name: spotinst
  spotinst:
    environment: env-eb36c360
  stage: dev
  # dev, test, or prod
  region: us-east-2
  environment:
    STAGE: ${opt:stage, self:provider.stage}
    # SECRET_VALUE: "${self:custom.secrets.SECRET_VALUE}"

plugins:
  - serverless-spotinst-functions
  - serverless-webpack

functions:
  # V1 - use semver, increment version appended when breaking changes made
  createV1:
    runtime: nodejs8.3
    memory: 128
    timeout: 30
    access: public
    handler: src/handler.createV1
  fetchV1:
    runtime: nodejs8.3
    memory: 128
    timeout: 30
    access: public
    handler: src/handler.fetchV1