service: serverless-boilerplate

custom:
  # enable for environment variables
  # #secrets: ${file(env.yml):prod}
  webpackIncludeModules: true

provider:
  name: spotinst
  runtime: nodejs6.10
  stage: dev
  # dev, test, or prod
  region: us-east-2
  environment:
    STAGE: ${opt:stage, self:provider.stage}
    # SECRET_VALUE: "${self:custom.secrets.SECRET_VALUE}"

plugins:
  - serverless-spotinst-functions
  - serverless-webpack
  - serverless-offline

functions:
  # V1 - use semver, increment version appended when breaking changes made
  createV1:
    handler: src/handler.createV1
    events:
      - http:
          path: V1/endpoint
          method: post
          cors: true
  fetchV1:
    handler: src/handler.fetchV1
    events:
      - http:
          path: V1/endpoint/{myParam}
          method: get
          cors: true